### ISSUE TITLE
CPU Utilisation is high

### ISSUE THREAD

**Issue by oubiwann** [robbielynch/ierlang#5]
One thing I noticed when running in both console and notebook was that CPU utilization hovered around 90-95% on my laptop. Not sure if you've seen this too.

I'll try to dig into this at some point ...

**Comment by robbielynch** [comment]
I just noticed this.
It was using 100% of my CPU.

I'm not 100% sure why, but my guess is that it's the `ierl_zmq_manager`. Because the code is constantly looping....

```erlang
%% Function to listen and respond on all sockets.
%% Constant loop keeps the kernel alive.
loop(HeartbeatSocket, ControlSocket, StdinSocket, ShellSocket, IOPubSocket)->
    %% Keep listening and responding
  loop(HeartbeatSocket, ControlSocket, StdinSocket, ShellSocket, IOPubSocket).
```

This also happens in the `ierl_shell_server`.

**Comment by Stelminator** [comment]
The loop in `ierl_zmq_manager` just needs a sleep or something to slow it down.  The loop in `ierl_shell_server` should be fine as is, since it blocks waiting for zmq messages.
